# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Auto-tar

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Get Current Release
      id: get_current_release
      uses: joutvhu/get-release@v1
      with:
        debug: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Archive using zip or tar
      uses: NSCoder/archive-action@v1.0.0
      
    - name: Tarball
      run: tar -czvf double_seals.tar.gz ./mods

    - name: Upload Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.get_current_release.outputs.upload_url }}
        asset_path: ./double_seals.tar.gz
        asset_name: double_seals.tar.gz
        asset_content_type: application/gzip
