# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Auto-build

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Archive using zip or tar
      uses: NSCoder/archive-action@v1.0.0
      
    - name: Tarball
      run: tar -czvf double_seals.tar.gz ./mods
